bottom_right_corner:
  x: 4.0
  y: 4.0
  z: 10.0
duration: 5.0
exposure: 10.0
folder: C:/Users/administrateur/PycharmProjects/GalvoControl/images/TEST
folder prefix: exp
freq: 20.0
steps:
  z_step: 20.0
upper_left_corner:
  x: 4.0
  y: 6.0
  z: 12.0
